# BUILD STAGE
# =========================
FROM node:22.13.0-alpine AS builder

WORKDIR /workspace

# NX root files
COPY package*.json nx.json tsconfig.base.json ./

# Copy full workspace
COPY apps ./apps

RUN npm ci --legacy-peer-deps

# Build đúng app NX
RUN npx nx run food-delivery:build


# =========================
# PRODUCTION STAGE
# =========================
FROM node:22.13.0-alpine

WORKDIR /app
ENV NODE_ENV=production

# Copy build output
COPY --from=builder /workspace/dist/apps/food-delivery ./dist
COPY --from=builder /workspace/package*.json ./

# Install only prod deps
RUN npm ci --omit=dev --legacy-peer-deps \
  && npm cache clean --force

# Prisma cần openssl
RUN apk add --no-cache openssl

# Security
USER node

EXPOSE 3000
CMD ["node", "dist/main.js"]
