# Stage 1: Build
FROM node:22.21.1-alpine3.23 AS builder

WORKDIR /app

COPY package*.json ./
COPY nx.json ./
COPY apps/food-delivery/project.json ./apps/food-delivery/
COPY apps/food-delivery/tsconfig*.json ./apps/food-delivery/

# Install all dependencies (dev + prod) để build
RUN npm ci --legacy-peer-deps

# Copy source code
COPY . .

# Build
RUN npx nx build food-delivery

# Stage 2: Run
FROM node:22.21.1-alpine3.23

WORKDIR /app

# Copy production node_modules
COPY package*.json ./

RUN npm ci --only=production

# Copy built dist
COPY --from=builder /app/dist/apps/food-delivery ./dist

EXPOSE 3000

CMD ["node", "dist/main.js"]
