# Dockerfile.dev
FROM node:22.21.1-alpine3.23

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install ALL dependencies (bao gồm devDependencies)
RUN npm ci --legacy-peer-deps

# Copy nx và tsconfig
COPY nx.json tsconfig.base.json .//
COPY apps/food-delivery/project.json ./apps/food-delivery/
COPY apps/food-delivery/tsconfig*.json ./apps/food-delivery/

# Expose port
EXPOSE 3000

# Chạy ở dev mode với watch
CMD ["npx", "nx", "serve", "food-delivery"]
